AppBundle\Entity\Lakers:
    type: entity
    table: lakers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
        year:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        team:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        selfscore:
            type: integer
            nullable: false
            options:
                unsigned: false
        oppscore:
            type: integer
            nullable: false
            options:
                unsigned: false
        dateplayed:
            type: date
            nullable: false
        winlose:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
        remark:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
